version: '3.8'

services:
  movie-catalog-service:
    build:
      context: .
      dockerfile: movie-catalog-service/Dockerfile
    container_name: movie-catalog-service
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
    volumes:
      - ./movie-catalog-service/data:/app/data
    networks:
      - movie-network

  movie-review-service:
    build:
      context: .
      dockerfile: movie-review-service/Dockerfile
    container_name: movie-review-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MOVIE_CATALOG_GRPC_HOST=movie-catalog-service:50051
    depends_on:
      - movie-catalog-service
    volumes:
      - ./movie-review-service/data:/app/data
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge
